version: '3.8'

services:
  clario-back:
    build:
      context: .
      target: production
    env_file:
      - ./.env
    depends_on:
      postgres_db:
        condition: service_started
    ports:
      - 8000:8000

  postgres_db:
    container_name: postgres_db
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
